# Generated by Django 4.0.5 on 2022-06-03 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_historicalusercustom_historicaluserowner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('catmen_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('catmen_description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría Del Menú',
                'verbose_name_plural': 'Categorías Del Menú',
                'db_table': 'CAT_MENU',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('res_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('res_description', models.TextField(verbose_name='Descripción')),
                ('res_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('res_slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('res_mainimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen Principal')),
                ('res_fkuserowner', models.ForeignKey(db_column='res_fkuserowner', on_delete=django.db.models.deletion.CASCADE, to='users.userowner', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Restaurantes',
                'verbose_name_plural': 'Restaurante',
                'db_table': 'RESTAURANT',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRestaurant',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('res_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('res_description', models.TextField(verbose_name='Descripción')),
                ('res_logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo')),
                ('res_slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('res_mainimage', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen Principal')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('res_fkuserowner', models.ForeignKey(blank=True, db_column='res_fkuserowner', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.userowner', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'historical Restaurantes',
                'verbose_name_plural': 'historical Restaurante',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('catmenite_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('catmenite_description', models.TextField(verbose_name='Descripción')),
                ('catmenite_for', models.PositiveSmallIntegerField(verbose_name='Para Cantidad De Personas')),
                ('catmenite_image', models.ImageField(upload_to='images/menu-item', verbose_name='Imagen')),
                ('catmenite_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('catmenite_fkcatmenu', models.ForeignKey(db_column='catmenite_fkcatmenu', on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorymenu', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'CAT_MENU_ITEM',
            },
        ),
        migrations.AddField(
            model_name='categorymenu',
            name='catmen_fkrestaurant',
            field=models.ForeignKey(db_column='catmen_fkrestaurant', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='Restaurante'),
        ),
    ]
