# Generated by Django 4.0.5 on 2022-06-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='CLIENT',
        ),
    ]
