# Generated by Django 4.0.5 on 2022-06-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluserowner_usu_fkgender_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymenu',
            name='catmen_fkrestaurant',
            field=models.ForeignKey(db_column='catmen_fkrestaurant', default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='categorymenuitem',
            name='catmenite_fkcatmenu',
            field=models.ForeignKey(db_column='catmenite_fkcatmenu', default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorymenu', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalcategorymenu',
            name='catmen_fkrestaurant',
            field=models.ForeignKey(blank=True, db_column='catmen_fkrestaurant', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restaurant.restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='historicalcategorymenuitem',
            name='catmenite_fkcatmenu',
            field=models.ForeignKey(blank=True, db_column='catmenite_fkcatmenu', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restaurant.categorymenu', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalrestaurant',
            name='res_fkuserowner',
            field=models.ForeignKey(blank=True, db_column='res_fkuserowner', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.userowner', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='res_fkuserowner',
            field=models.ForeignKey(db_column='res_fkuserowner', default='', on_delete=django.db.models.deletion.CASCADE, to='users.userowner', verbose_name='Propietario'),
        ),
    ]
