# Generated by Django 4.0.5 on 2022-06-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('restaurant', '0002_alter_client_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='emp_fkgender',
            field=models.ForeignKey(db_column='emp_fkgender', default=2, on_delete=django.db.models.deletion.CASCADE, to='users.categorygender', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_fkrol',
            field=models.ForeignKey(db_column='emp_fkrol', default='1', on_delete=django.db.models.deletion.CASCADE, to='users.categoryrol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='historicalempleado',
            name='emp_fkgender',
            field=models.ForeignKey(blank=True, db_column='emp_fkgender', db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categorygender', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='historicalempleado',
            name='emp_fkrol',
            field=models.ForeignKey(blank=True, db_column='emp_fkrol', db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categoryrol', verbose_name='Rol'),
        ),
    ]
