# Generated by Django 4.0.5 on 2022-06-03 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('catgen_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('catgen_description', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'CAT_GENDER',
            },
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('usu_age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('usu_address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('usu_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('usu_fkuser', models.ForeignKey(db_column='acc_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('usu_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categorygender', verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USER_CUSTOM',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserCustom',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('usu_age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('usu_address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('usu_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usu_fkuser', models.ForeignKey(blank=True, db_column='acc_fkuser', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('usu_gender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categorygender', verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryGender',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('catgen_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('catgen_description', models.CharField(max_length=50, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Genero',
                'verbose_name_plural': 'historical Generos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
