# Generated by Django 4.0.5 on 2022-06-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserowner',
            name='usu_fkrol',
            field=models.ForeignKey(blank=True, db_column='usu_fkrol', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categoryrol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='historicaluserowner',
            name='usu_fkuser',
            field=models.ForeignKey(blank=True, db_column='usu_fkuser', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='usu_fkrol',
            field=models.ForeignKey(db_column='usu_fkrol', on_delete=django.db.models.deletion.CASCADE, to='users.categoryrol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='usu_fkuser',
            field=models.ForeignKey(db_column='usu_fkuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
