# Generated by Django 4.0.5 on 2022-06-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_historicaluserowner_usu_fkrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserowner',
            name='usu_fkgender',
            field=models.ForeignKey(blank=True, db_column='usu_fkgender', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categorygender', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='historicaluserowner',
            name='usu_fkrol',
            field=models.ForeignKey(blank=True, db_column='usu_fkrol', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.categoryrol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='historicaluserowner',
            name='usu_fkuser',
            field=models.ForeignKey(blank=True, db_column='usu_fkuser', db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='usu_fkgender',
            field=models.ForeignKey(db_column='usu_fkgender', default='', on_delete=django.db.models.deletion.CASCADE, to='users.categorygender', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='usu_fkrol',
            field=models.ForeignKey(db_column='usu_fkrol', default='', on_delete=django.db.models.deletion.CASCADE, to='users.categoryrol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='usu_fkuser',
            field=models.ForeignKey(db_column='usu_fkuser', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
