# Generated by Django 4.0.5 on 2022-06-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_historicalusercustom_usu_fkgender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha De Creación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cli_fkusercustom', models.ForeignKey(blank=True, db_column='cli_fkusercustom', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.usercustom', verbose_name='Usuario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha De Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha De Creación')),
                ('cli_fkusercustom', models.ForeignKey(db_column='cli_fkusercustom', on_delete=django.db.models.deletion.CASCADE, to='users.usercustom', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
