# Generated by Django 4.0.5 on 2022-06-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalclient_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='CLIENTS',
        ),
    ]
